/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoPI.view;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import projetoPI.DAO.ProdutoDAO;

import projetoPI.controller.ProdutoController;
import projetoPI.model.Produto;

public final class ListaProdutoView extends javax.swing.JFrame {
    private String modoTela;
    public CadastroVendaView telaVenda = new CadastroVendaView();
    
    public ListaProdutoView() {
        
        initComponents();
        
        
        this.setLocationRelativeTo(null);
         tblProduto.setVisible(false);
        
       // LoadTable();
        //  tblProduto.setVisible(true);
    }

    public void LoadTable() {
        ArrayList<String[]> listaProdutos = ProdutoController.getProdutos();

        DefaultTableModel tmProduto = new DefaultTableModel();

        tmProduto.addColumn("ID");
        tmProduto.addColumn("Nome");
        tmProduto.addColumn("Estoque");
        tmProduto.addColumn("Valor");
          tmProduto.addColumn("Categoria");
        tblProduto.setModel(tmProduto);
        for (String[] c : listaProdutos) {
            tmProduto.addRow(c);
        }

        //Defino o tamanho para cada coluna
        // tmProduto.getColumnModel().getColumn(0).setPreferredWidth(50); //ID
        tblProduto.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblProduto.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
         tblProduto.getColumnModel().getColumn(4).setPreferredWidth(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        categoriaBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compra Personalizada");
        setResizable(false);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/yellow-archive-icon.png"))); // NOI18N

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome do Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setText("Selecione Produto");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/blue-search-icon.png"))); // NOI18N
        btnPesquisar.setText("Pesquisa");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        categoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cama, Mesa e Banho", "Utensílios Doméstios ", "Decoração", "Iluminação", "Móveis" }));
        categoriaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnPesquisar)))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/green-ok-icon.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/red-cross-icon (1).png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelecionar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed

     if(tblProduto.getRowCount() > 0){
         int id = tblProduto.getSelectedRow();
         buscaProduto(id);
         selecionaProduto();
         selId();
         selNome();
         //Passar os dados para a tela de venda
         this.telaVenda.definirCodigoProduto(selId());
         this.telaVenda.definirNomeProduto(selNome());
          this.telaVenda.definirEstoque(selEstoque());
           this.telaVenda.definirValor(selValor());
        
         
     }
     this.dispose();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:     
        //LoadTable();
        if(!ProdutoController.getProdutos().isEmpty()){
            
        
            String categoria = categoriaBox.getSelectedItem().toString();
// String categoria = String.valueOf(categoriaBox.getSelectedItem());
            if (categoria.equals(categoriaBox.getSelectedItem().toString())) 
            {
                buscaProduto(categoria);
             

            } else {
                JOptionPane.showMessageDialog(this, "Produtos não selecionado!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Produtos não selecionado!");
        }


    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void categoriaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_categoriaBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaProdutoView().setVisible(true);
            }
        });
    }

    public void buscaProduto(String categoria) {
        ArrayList<String[]> listaProdutos = ProdutoController.buscaProduto(categoria);
         tblProduto.setVisible(true);
        if (!listaProdutos.isEmpty()) {

            DefaultTableModel tmProduto = new DefaultTableModel();
            tmProduto.addColumn("ID");
            tmProduto.addColumn("Nome");
            tmProduto.addColumn("Estoque");
            tmProduto.addColumn("Valor");
             tmProduto.addColumn("Categoria");
            for (String[] p : listaProdutos) {
                tmProduto.addRow(p);
            }

            tblProduto.setModel(tmProduto);
            tblProduto.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblProduto.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
             tblProduto.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblProduto.setVisible(true);
        } else {
            tblProduto.setVisible(false);
    
           JOptionPane.showMessageDialog(this, "Não há nenhum produto cadastrado na categoria: "+categoria+ "!");
        }

    }
 public void buscaProduto(int id) {
        ArrayList<String[]> listaProdutos = ProdutoController.buscaProduto(id);

        if (!listaProdutos.isEmpty()) {

            DefaultTableModel tmProduto = new DefaultTableModel();
            tmProduto.addColumn("ID");
            tmProduto.addColumn("Nome");
            tmProduto.addColumn("Estoque");
            tmProduto.addColumn("Valor");
               tmProduto.addColumn("Categoria");
            for (String[] p : listaProdutos) {
                tmProduto.addRow(p);
            }

            tblProduto.setModel(tmProduto);
            tblProduto.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblProduto.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblProduto.setVisible(true);
        } else {
            tblProduto.setVisible(false);
            JOptionPane.showMessageDialog(this, "Produto selecionado!");
        }

    

    }
    public Object[] selecionaProduto(){
         DefaultTableModel model = (DefaultTableModel) tblProduto.getModel();
         int nRow = model.getRowCount();
          Object [] dadosTabela = new Object[nRow];
          for (int i =0; i< nRow; i++){
                 dadosTabela [i] = tblProduto.getSelectedRow();
                  
             
          }
        return dadosTabela;
    }
    public int selId(){
        int id = (Integer.parseInt((String) tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 0)));
        return id;
    }
    public String selNome(){
        String nome = (tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 1).toString());
        return nome;
    }
    
     
    public String selEstoque(){
        String estoque = (tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 2).toString());
        return estoque;
    }

 
    public String selValor(){
        String valor =  (tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 3).toString());
        return valor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox<String> categoriaBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduto;
    // End of variables declaration//GEN-END:variables
}
